### ISSUE TITLE
Don't use https for github in our documentation

### ISSUE THREAD

**Issue by tkittel** [mctools/dgcode#11]
On

https://confluence.esss.lu.se/display/DGCODE/Git

We are still telling people to use github over https rather than ssh. I guess that doesn't work.

**Comment by MilanKlausz** [comment]
It doesn't work with the account password, but it would [work with a Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#https). 
In any case, I've changed the suggested method for github to SSH, and added a link to github about how to set it up. (+mentioned the possible alternative of using a Personal Access Token)
