### ISSUE TITLE
seg fault in ess_griffanatests_testextract

### ISSUE THREAD

**Issue by tkittel** [mctools/dgcode#3]
Seg-fault, only on ubuntu22 + clang and only in release build:

https://github.com/mctools/dgcode/actions/runs/3327354892/jobs/5502075125

```
====>
427
====> Last 20 lines from ess_griffanatests_testextract/output.log:
428
====>
429
Extracted 1 events from input file into new file out.griff
430
GriffDataReader opened file 10evts_singleneutron_on_b10_reduced.griff
431
Copied event #0 to output file
432
Copied event #1 to output file
433
Copied event #2 to output file
434
Copied event #3 to output file
435
Copied event #4 to output file
436
Copied event #5 to output file
437
Copied event #6 to output file
438
Copied event #7 to output file
439
Copied event #8 to output file
440
Copied event #9 to output file
441
No more events requested from input file - ending.
442
Extracted 10 events from input file into new file out.griff
443
GriffDataReader opened file 10evts_singleneutron_on_b10_reduced.griff
444
Copied event #0 to output file
445
Copied event #7 to output file
446
No more events requested from input file - ending.
447
Extracted 2 events from input file into new file out.griff
448
/home/runner/work/dgcode/dgcode/projects/install/scripts/ess_griffanatests_testextract: line 11: 12994 Segmentation fault      (core dumped) ess_griffformat_dumpfile out.griff
449
====> (end of ess_griffanatests_testextract/output.log)
```

**Comment by MilanKlausz** [comment]
I've created a [test_debugging_with_tmate](https://github.com/mctools/dgcode_actions/actions/workflows/test_debugging_with_tmate.yml) workflow that uses the [Debugging with tmate](https://github.com/marketplace/actions/debugging-with-tmate) GH action, which allows connecting to github runner through ssh or a web sell: 

- dispatch the workflow manually
- wait until it stops at the 'Setup tmate session' step (right after the 'Run tests' step)
- open the log of this step to find the ssh connection string or link to the web shell
- Don't forget to run:
. $GITHUB_WORKSPACE/dgdepfixerInstall/setup.sh
export DGCODE_EXTRA_PKG_PATH="$GITHUB_WORKSPACE/dgcode_val"
cd $GITHUB_WORKSPACE/projects
. bootstrap.sh

Note: press q in the blank web shell (the message that appears in the terminal through ssh doesn't appear in the web shell)

**Comment by tkittel** [comment]
Very cool @MilanKlausz !! So that already tells me that the seg fault happens in:
```
python -c 'import GriffFormat.dumpfile'
```
But I have to run now unfortunately, I don't see anything obviously wrong...

**Comment by tkittel** [comment]
Trying locally to see if a new dgboost version (#18) would help. With that, I get a segfault in a different test, in GriffDataRead/pycpp__init/materials.hh. It appears related to the `py_elem_iter` and `py_isotope_iter`, which gets destructed more often than constructed. Too be investigated.

**Comment by tkittel** [comment]
Commit a22fada fixes a segfault I observed when testing out dgboost v1.80, but I am not actually sure that it alone will fix the problem in the present issue, so reopening.

**Comment by tkittel** [comment]
Sigh... did you check @MilanKlausz if this is easy to reproduce locally on a mac? In any case, I probably won't have much time until next week.

**Comment by tkittel** [comment]
I think I managed to make a function which can decode this `LINKER:` syntax, which we can use. For reference it and a few test calls are included here. I will add it as a utility function in dgcode and use it in the `ExtDep_Python.cmake` file. It might be we should use it elsewhere as well, but for now let us see if this resolves the immediate issue:

```cmake
cmake_minimum_required(VERSION 3.12.4...3.24.2)

project(DUMMY LANGUAGES C)

function( decode_link_options link_options language resvar )
  #Decodes the LINKER: syntax
  #(cf. https://cmake.org/cmake/help/latest/command/add_link_options.html)

  if( "${CMAKE_VERSION}" VERSION_LESS "3.13.0")
    #LINKER: syntax not introduced yet:
    set( ${resvar} "${link_options}" PARENT_SCOPE )
  endif()

  if ( link_options MATCHES "SHELL:" )
    message(FATAL_ERROR "\"SHELL:\" syntax encountered in link options. This is currently not supported.")
  endif()

  if ( NOT link_options MATCHES "LINKER:" )
    set( ${resvar} "${link_options}" PARENT_SCOPE )
    return()
  endif()
  string(REPLACE " " ";" link_opts_list "${link_options}")
  list(JOIN CMAKE_${language}_LINKER_WRAPPER_FLAG " " wrapflag )
  if ( wrapflag MATCHES "  $")
    string(REGEX REPLACE "  $" " " wrapflag "${wrapflag}")
  endif()
  #set( wrapflag "${CMAKE_${language}_LINKER_WRAPPER_FLAG}" )
  if ( DEFINED CMAKE_${language}_LINKER_WRAPPER_FLAG_SEP )
    set( has_wrapflagsep ON )
    set( wrapflagsep "${CMAKE_${language}_LINKER_WRAPPER_FLAG_SEP}" )
  else()
    set( has_wrapflagsep OFF )
  endif()

  set(tmp "")
  foreach( elem ${link_opts_list} )
    if (  elem MATCHES "^LINKER:" )
      string(SUBSTRING "${elem}" 7 -1 elem )
      if ( NOT elem MATCHES "," )
        list(APPEND tmp "${wrapflag}${elem}")
      else()
        if ( has_wrapflagsep )
          string(REPLACE "," "${wrapflagsep}" elem "${elem}")
          list(APPEND tmp "${wrapflag}${elem}")
        else()
          string(REPLACE "," " ${wrapflag}" elem "${elem}")
          list(APPEND tmp "${wrapflag}${elem}")
        endif()
      endif()
    else()
      list(APPEND tmp "${elem}")
    endif()
  endforeach()
  list(JOIN tmp " " tmp)
  set( ${resvar} "${tmp}" PARENT_SCOPE )
endfunction()

function(test teststr)
  message("")
  message("IN : ${teststr}")
  decode_link_options( "${teststr}" C out )
  message("OUT: ${out}")
endfunction()

test("hejsa -a -b      -c")
test("hejsa -a -b -c")
test("hejsa -a -b   \n   -c")
test("LINKER:w bla")
test("--justaflag LINKER:-z,defs bla.so")

#gcc:
test("LINKER:-z,defs")

#clang:
message("------------------------")
message("Clang test (should give \"-Xlinker -z -Xlinker defs\")")
set (CMAKE_C_LINKER_WRAPPER_FLAG "-Xlinker" " ")
unset(CMAKE_C_LINKER_WRAPPER_FLAG_SEP)
test("LINKER:-z,defs")

#gcc:
message("------------------------")
message("GCC test (should give \"-Wl,-z,defs\")")
set (CMAKE_C_LINKER_WRAPPER_FLAG "-Wl,")
set(CMAKE_C_LINKER_WRAPPER_FLAG_SEP ",")
test("LINKER:-z,defs")

#sunpro:
message("------------------------")
message("sunpro test (should give \"-Qoption ld -z,defs\")")
set (CMAKE_C_LINKER_WRAPPER_FLAG "-Qoption" "ld" " ")
set (CMAKE_C_LINKER_WRAPPER_FLAG_SEP ",")
test("LINKER:-z,defs")
```

**Comment by tkittel** [comment]
Making the changes now. Instead of editing ExtDep_Python.cmake, I simply decode all link options in WriteResults.cmake just before extraction, which hopefully means that it will catch all future issues of the same kind.

Btw., our cmake `project()` call was missing `LANGUAGES C CXX` parameters, which baffles me a bit.

**Comment by tkittel** [comment]
Pushed now, let is see if I broke everything (well, my ubuntu where there are no `LINKER:` flags did not break).
