### ISSUE TITLE
Split up build and test steps in workflows

### ISSUE THREAD

**Issue by tkittel** [mctools/dgcode#8]
Hi @MilanKlausz. Can we split up the build and tests steps in the workflows? Because then we can immediately see if it is a build or tests failure.

And actually, can we perhaps split up the build step further, into framework and non-framework parts? That should give a nicer overview.

I.e. instead of just launching "dgbuild -at [-d]" we could have three steps corresponding to the three commands: 
```
dgbuild [-d] ONLY='Framework::*'
dgbuild [-d] ONLY='*'
dgbuild [-d] ONLY='*' -t [--whateverothertestoptions we use]
```
In the last step I assume there are some relevant options (--numexcept IIRC?).
Of course, this is not useful if the three steps are not running in the same directories, we do after all not want to actually build any package more than once.

**Comment by tkittel** [comment]
Actually I see now that this is done in all final per-repo .yml, and not in the central actions, right?

**Comment by MilanKlausz** [comment]
Yes, this is actually and issue for the dgcode_actions repo, but I might as well react here:

- The run-tests.yml and run-private-proj-tests.yml workflows in this repo (dgcode) simply [reuse](https://docs.github.com/en/actions/using-workflows/reusing-workflows) the run_user_tests.yml, run_validation_tests.yml and run_private_projects_tests.yml workflows in the dgcode_actions repo, so everything relevant happens there.
- All these 3 workflows use the dgcode_actions/[setup](https://github.com/mctools/dgcode_actions/blob/main/.github/actions/setup/action.yml) action to setup the framework: checkout the code, install prereqs, create dgdepfixer, install optional sw (only Geant4 for now), and finally, build the framework packages. (So the 'building the framework pkgs separately' part is already satisfied.)
- Then the 3 workflows used to build the respective non-framework packages (validation/public/private), and run the tests in one step, but now I've separated them into a 'Build ... packages' and 'Run tests' steps.

Note: The same 'Projects' directory is used to build all packages (which is empty..except for the bootstrap file). The non-framework packages are added to the pkg search path through the the DGCODE_EXTRA_PKG_PATH env var after(!) the framework packages are build.
